name: ZAP

on: push

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
      options: --user root -v ${{ github.workspace }}:/zap/wrk/:rw
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd && ls -l
          pip install --upgrade pip github3.py
          pip3 install --upgrade pip github3.py
      - name: run zap baseline scan
        id: scan
        run: |
          zap-baseline.py -t https://selfservice-dev.pathfinder.gov.bc.ca/ -g .github/workflows/zap-rules/rules.tsv -w zapdevreport.md || echo 0
          echo "::set-output name=text::$(<zapdevreport.md)";
          cat zapdevreport.md | curl -X POST --data-urlencode "payload={\"text\": \"$(</dev/stdin)\"}" ${{ secrets.ZAP_SCAN_WEBHOOK_URL }}
